export const LECTURER_ERROR = "LECTURER_ERROR";
export const GET_LECTURER = "GET_LECTURER";
export const POST_LECTURER = "POST_LECTURER";
export const DELETE_LECTURER = "DELETE_LECTURER";
export const VIEW_LECTURER = "VIEW_LECTURER";
export const DELETE_LECTURER_COURSE = "DELETE_LECTURER_COURSE";

export const COURSES_ERROR = "COURSES_ERROR";
export const GET_COURSES = "GET_COURSES";
export const POST_COURSES = "POST_COURSES";
export const DELETE_COURSES = "DELETE_COURSES";
export const VIEW_COURSE = "VIEW_COURSE";
